version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
    ports:
      - 3000:8080
    depends_on:
      - mysql_db
    env_file: .env
    networks:
      - node-nestwork

mysql_db:
  image: mysql
  container_name: mysql_db
  ports:
    - 3307:3306
  environment:
    - MYSQL_ROOT_PASSWORD=080201010723
    - MYSQL_DATABASE=capstone_airbnb
  env_file:
    - .env
  volumes:
    - mysql_db:/var/lib/mysql
  networks:
    - node-network

volumes:
  mysql_db:
    driver: local
networks:
  node-network:
